# -*- makefile -*-


# IMPORTANT: should be set to e.g. -deb, -ydl -mdk if the source is patched
VENDOR		:= 


#################################################################
# No serviceable parts below
#################################################################

VERSION		:= 0.9.72
EXTRA_VERSION	:= -pre1$(VENDOR)
RELEASENAME	:= $(VERSION)$(EXTRA_VERSION)$(VENDOR)

top_srcdir	:= $(shell \
			test -f configure.in && { echo . ; exit 0 ; } ; \
			test -f ../configure.in && { echo .. ; exit 0 ; } ; \
			test -f ../../configure.in && { echo ../.. ; exit 0 ; } ; \
			test -f ../../../configure.in && { echo ../../.. ; exit 0 ; } ; \
			test -f ../../../../configure.in && { echo ../../../.. ; exit 0 ; } ; \
			test -f ../../../../../configure.in && { echo ../../../../.. ; exit 0 ; } )
srcdir		:= $(top_srcdir)/src
scriptdir	:= $(top_srcdir)/scripts
rules		:= $(top_srcdir)/rules

ARCH    	:= $(shell $(scriptdir)/archname $$ARCH)
export		ARCH

MOLDIR		= ../../../src
IDIRS		= -I. -I$(ARCHINCLUDES) -I./include -I$(srcdir)/include \
		  -I${MOLDIR}/shared -I${MOLDIR}/include -I${MOLDIR}/drivers/include \
		  -I${MOLDIR}/drivers/disk/include $(INCLUDES)

all:

-include	$(top_srcdir)/rules/Makefile.defs

ODIR		= .objs-$(ARCH)
ARCHINCLUDES	= $(top_srcdir)/.inc-$(ARCH)
DISTCLEANFILES	= .objs-*

LIBGCC		= `$(CC) -print-libgcc-file-name`
