.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.de It
.TP 4.6cm
.B " \\$1 "
..
.de It2
.TP 3cm
.B " \\$1 "
..
.TH MOLVCONFIG 8 "12 August 2001" "Mac-on-Linux" "System Reference Manual"
.SH NAME
.B molvconfig
\- configure full\-screen video modes for Mac\-on\-Linux
.SH SYNOPSIS
.B molvconfig
.SH DESCRIPTION
The \fImolvconfig\fR program configures is used to
configure full\-screen video modes for Mac\-on\-Linux.

.fi
.SH FILES
.nf
\fI/etc/molrc\fR    \- Mac\-on\-Linux configuration file
.fi
.SH BUGS
This man page is not complete...
.SH AUTHORS
This man page was written by Samuel Rydh <samuel@ibrium.se>.
.P
.SH REPORTING BUGS
Bugs in \fBmolvconfig\fR should be reported to Samuel Rydh <samuel@ibrium.se>.
.SH SEE ALSO
.BR startmol (1),
.BR molrc (5)
